CREATE TABLE USER (
  USERID       INT UNSIGNED  NOT NULL,
  LOGINID      VARCHAR(64)   NOT NULL,
  NAME_JA      VARCHAR(64)   NOT NULL,
  NAME_EN      VARCHAR(64)   NOT NULL,
  PASSWORD     VARCHAR(64)   NOT NULL,
  FACEBOOK_UID VARCHAR(256),
  GITHUB_UID   VARCHAR(256),
  GOOGLE_UID   VARCHAR(256),
  PRIMARY KEY (USERID)
);

INSERT INTO USER(
    USERID, LOGINID, NAME_JA, NAME_EN, PASSWORD) 
  VALUES (
    0, 'admin', '管理者', 'administrator', 'admin');