CREATE TABLE USER (
  USERID       VARCHAR(64)  NOT NULL,
  NAME_JA      VARCHAR(64)  NOT NULL,
  NAME_EN      VARCHAR(64)  NOT NULL,
  PASSWORD     VARCHAR(64)  NOT NULL,
  FACEBOOK_UID VARCHAR(256) NOT NULL,
  GITHUB_UID   VARCHAR(256) NOT NULL,
  GOOGLE_UID   VARCHAR(256) NOT NULL,
  PRIMARY KEY (USERID)
);